package crm_structures

type CreateContacts struct {
	Attributes struct {
		Accountrolecode                 int    `json:"accountrolecode"`
		Address1Addressid               string `json:"address1_addressid"`
		Address1Addresstypecode         int    `json:"address1_addresstypecode"`
		Address1City                    string `json:"address1_city"`
		Address1Composite               string `json:"address1_composite"`
		Address1Country                 string `json:"address1_country"`
		Address1County                  string `json:"address1_county"`
		Address1Fax                     string `json:"address1_fax"`
		Address1Freighttermscode        int    `json:"address1_freighttermscode"`
		Address1Latitude                int    `json:"address1_latitude"`
		Address1Line1                   string `json:"address1_line1"`
		Address1Line2                   string `json:"address1_line2"`
		Address1Line3                   string `json:"address1_line3"`
		Address1Longitude               int    `json:"address1_longitude"`
		Address1Name                    string `json:"address1_name"`
		Address1Postalcode              string `json:"address1_postalcode"`
		Address1Postofficebox           string `json:"address1_postofficebox"`
		Address1Primarycontactname      string `json:"address1_primarycontactname"`
		Address1Shippingmethodcode      int    `json:"address1_shippingmethodcode"`
		Address1Stateorprovince         string `json:"address1_stateorprovince"`
		Address1Telephone1              string `json:"address1_telephone1"`
		Address1Telephone2              string `json:"address1_telephone2"`
		Address1Telephone3              string `json:"address1_telephone3"`
		Address1Upszone                 string `json:"address1_upszone"`
		Address1Utcoffset               int    `json:"address1_utcoffset"`
		Address2Addressid               string `json:"address2_addressid"`
		Address2Addresstypecode         int    `json:"address2_addresstypecode"`
		Address2City                    string `json:"address2_city"`
		Address2Composite               string `json:"address2_composite"`
		Address2Country                 string `json:"address2_country"`
		Address2County                  string `json:"address2_county"`
		Address2Fax                     string `json:"address2_fax"`
		Address2Freighttermscode        int    `json:"address2_freighttermscode"`
		Address2Latitude                int    `json:"address2_latitude"`
		Address2Line1                   string `json:"address2_line1"`
		Address2Line2                   string `json:"address2_line2"`
		Address2Line3                   string `json:"address2_line3"`
		Address2Longitude               int    `json:"address2_longitude"`
		Address2Name                    string `json:"address2_name"`
		Address2Postalcode              string `json:"address2_postalcode"`
		Address2Postofficebox           string `json:"address2_postofficebox"`
		Address2Primarycontactname      string `json:"address2_primarycontactname"`
		Address2Shippingmethodcode      int    `json:"address2_shippingmethodcode"`
		Address2Stateorprovince         string `json:"address2_stateorprovince"`
		Address2Telephone1              string `json:"address2_telephone1"`
		Address2Telephone2              string `json:"address2_telephone2"`
		Address2Telephone3              string `json:"address2_telephone3"`
		Address2Upszone                 string `json:"address2_upszone"`
		Address2Utcoffset               int    `json:"address2_utcoffset"`
		Address3Addressid               string `json:"address3_addressid"`
		Address3Addresstypecode         int    `json:"address3_addresstypecode"`
		Address3City                    string `json:"address3_city"`
		Address3Composite               string `json:"address3_composite"`
		Address3Country                 string `json:"address3_country"`
		Address3County                  string `json:"address3_county"`
		Address3Fax                     string `json:"address3_fax"`
		Address3Freighttermscode        int    `json:"address3_freighttermscode"`
		Address3Latitude                int    `json:"address3_latitude"`
		Address3Line1                   string `json:"address3_line1"`
		Address3Line2                   string `json:"address3_line2"`
		Address3Line3                   string `json:"address3_line3"`
		Address3Longitude               int    `json:"address3_longitude"`
		Address3Name                    string `json:"address3_name"`
		Address3Postalcode              string `json:"address3_postalcode"`
		Address3Postofficebox           string `json:"address3_postofficebox"`
		Address3Primarycontactname      string `json:"address3_primarycontactname"`
		Address3Shippingmethodcode      int    `json:"address3_shippingmethodcode"`
		Address3Stateorprovince         string `json:"address3_stateorprovince"`
		Address3Telephone1              string `json:"address3_telephone1"`
		Address3Telephone2              string `json:"address3_telephone2"`
		Address3Telephone3              string `json:"address3_telephone3"`
		Address3Upszone                 string `json:"address3_upszone"`
		Address3Utcoffset               int    `json:"address3_utcoffset"`
		Aging30                         int    `json:"aging30"`
		Aging30Base                     int    `json:"aging30_base"`
		Aging60                         int    `json:"aging60"`
		Aging60Base                     int    `json:"aging60_base"`
		Aging90                         int    `json:"aging90"`
		Aging90Base                     int    `json:"aging90_base"`
		Anniversary                     int    `json:"anniversary"`
		Annualincome                    int    `json:"annualincome"`
		AnnualincomeBase                int    `json:"annualincome_base"`
		Assistantname                   string `json:"assistantname"`
		Assistantphone                  string `json:"assistantphone"`
		Birthdate                       int    `json:"birthdate"`
		Business2                       string `json:"business2"`
		Callback                        string `json:"callback"`
		Childrensnames                  string `json:"childrensnames"`
		Company                         string `json:"company"`
		Contactid                       string `json:"contactid"`
		Createdby                       string `json:"createdby"`
		Createdon                       int    `json:"createdon"`
		Createdonbehalfby               string `json:"createdonbehalfby"`
		Creditlimit                     int    `json:"creditlimit"`
		CreditlimitBase                 int    `json:"creditlimit_base"`
		Creditonhold                    bool   `json:"creditonhold"`
		Customersizecode                int    `json:"customersizecode"`
		Customertypecode                int    `json:"customertypecode"`
		Defaultpricelevelid             string `json:"defaultpricelevelid"`
		Department                      string `json:"department"`
		Description                     string `json:"description"`
		Donotbulkemail                  bool   `json:"donotbulkemail"`
		Donotbulkpostalmail             bool   `json:"donotbulkpostalmail"`
		Donotemail                      bool   `json:"donotemail"`
		Donotfax                        bool   `json:"donotfax"`
		Donotphone                      bool   `json:"donotphone"`
		Donotpostalmail                 bool   `json:"donotpostalmail"`
		Donotsendmm                     bool   `json:"donotsendmm"`
		Educationcode                   int    `json:"educationcode"`
		Emailaddress1                   string `json:"emailaddress1"`
		Emailaddress2                   string `json:"emailaddress2"`
		Emailaddress3                   string `json:"emailaddress3"`
		Employeeid                      string `json:"employeeid"`
		Entityimage                     string `json:"entityimage"`
		EntityimageTimestamp            int    `json:"entityimage_timestamp"`
		EntityimageURL                  string `json:"entityimage_url"`
		Entityimageid                   string `json:"entityimageid"`
		Exchangerate                    int    `json:"exchangerate"`
		Externaluseridentifier          string `json:"externaluseridentifier"`
		Familystatuscode                int    `json:"familystatuscode"`
		Fax                             string `json:"fax"`
		Firstname                       string `json:"firstname"`
		Followemail                     bool   `json:"followemail"`
		Ftpsiteurl                      string `json:"ftpsiteurl"`
		Fullname                        string `json:"fullname"`
		Gendercode                      int    `json:"gendercode"`
		Governmentid                    string `json:"governmentid"`
		Haschildrencode                 int    `json:"haschildrencode"`
		Home2                           string `json:"home2"`
		Importsequencenumber            int    `json:"importsequencenumber"`
		Isbackofficecustomer            bool   `json:"isbackofficecustomer"`
		Jobtitle                        string `json:"jobtitle"`
		Lastname                        string `json:"lastname"`
		Lastonholdtime                  int    `json:"lastonholdtime"`
		Lastusedincampaign              int    `json:"lastusedincampaign"`
		Leadsourcecode                  int    `json:"leadsourcecode"`
		Managername                     string `json:"managername"`
		Managerphone                    string `json:"managerphone"`
		Marketingonly                   bool   `json:"marketingonly"`
		Masterid                        string `json:"masterid"`
		Merged                          bool   `json:"merged"`
		Middlename                      string `json:"middlename"`
		Mobilephone                     string `json:"mobilephone"`
		Modifiedby                      string `json:"modifiedby"`
		Modifiedon                      int    `json:"modifiedon"`
		Modifiedonbehalfby              string `json:"modifiedonbehalfby"`
		Nickname                        string `json:"nickname"`
		Numberofchildren                int    `json:"numberofchildren"`
		Onholdtime                      int    `json:"onholdtime"`
		Originatingleadid               string `json:"originatingleadid"`
		Overriddencreatedon             int    `json:"overriddencreatedon"`
		Ownerid                         string `json:"ownerid"`
		Owningbusinessunit              string `json:"owningbusinessunit"`
		Owningteam                      string `json:"owningteam"`
		Owninguser                      string `json:"owninguser"`
		Pager                           string `json:"pager"`
		Parentcustomerid                string `json:"parentcustomerid"`
		ParentcustomeridAccount         string `json:"parentcustomerid_account"`
		ParentcustomeridContact         string `json:"parentcustomerid_contact"`
		Participatesinworkflow          bool   `json:"participatesinworkflow"`
		Paymenttermscode                int    `json:"paymenttermscode"`
		Preferredappointmentdaycode     int    `json:"preferredappointmentdaycode"`
		Preferredappointmenttimecode    int    `json:"preferredappointmenttimecode"`
		Preferredcontactmethodcode      int    `json:"preferredcontactmethodcode"`
		Preferredequipmentid            string `json:"preferredequipmentid"`
		Preferredserviceid              string `json:"preferredserviceid"`
		Preferredsystemuserid           string `json:"preferredsystemuserid"`
		Processid                       string `json:"processid"`
		Salutation                      string `json:"salutation"`
		Shippingmethodcode              int    `json:"shippingmethodcode"`
		SLAContactSLA                   string `json:"sla_contact_sla"`
		SlainvokedidContactSLA          string `json:"slainvokedid_contact_sla"`
		Spousesname                     string `json:"spousesname"`
		Stageid                         string `json:"stageid"`
		StageidProcessstage             string `json:"stageid_processstage"`
		Statecode                       int    `json:"statecode"`
		Statuscode                      int    `json:"statuscode"`
		Subscriptionid                  string `json:"subscriptionid"`
		Suffix                          string `json:"suffix"`
		Telephone1                      string `json:"telephone1"`
		Telephone2                      string `json:"telephone2"`
		Telephone3                      string `json:"telephone3"`
		Territorycode                   int    `json:"territorycode"`
		Timespentbymeonemailandmeetings string `json:"timespentbymeonemailandmeetings"`
		Timezoneruleversionnumber       int    `json:"timezoneruleversionnumber"`
		Transactioncurrencyid           string `json:"transactioncurrencyid"`
		Traversedpath                   string `json:"traversedpath"`
		Utcconversiontimezonecode       int    `json:"utcconversiontimezonecode"`
		Versionnumber                   int    `json:"versionnumber"`
		Websiteurl                      string `json:"websiteurl"`
		Yomifirstname                   string `json:"yomifirstname"`
		Yomifullname                    string `json:"yomifullname"`
		Yomilastname                    string `json:"yomilastname"`
		Yomimiddlename                  string `json:"yomimiddlename"`
	} `json:"attributes"`
	FetchMetaInfo bool `json:"fetchMetaInfo"`
}
type GetContacts struct {
	Attributes struct {
		Accountrolecode                 int    `json:"accountrolecode"`
		Address1Addressid               string `json:"address1_addressid"`
		Address1Addresstypecode         int    `json:"address1_addresstypecode"`
		Address1City                    string `json:"address1_city"`
		Address1Composite               string `json:"address1_composite"`
		Address1Country                 string `json:"address1_country"`
		Address1County                  string `json:"address1_county"`
		Address1Fax                     string `json:"address1_fax"`
		Address1Freighttermscode        int    `json:"address1_freighttermscode"`
		Address1Latitude                int    `json:"address1_latitude"`
		Address1Line1                   string `json:"address1_line1"`
		Address1Line2                   string `json:"address1_line2"`
		Address1Line3                   string `json:"address1_line3"`
		Address1Longitude               int    `json:"address1_longitude"`
		Address1Name                    string `json:"address1_name"`
		Address1Postalcode              string `json:"address1_postalcode"`
		Address1Postofficebox           string `json:"address1_postofficebox"`
		Address1Primarycontactname      string `json:"address1_primarycontactname"`
		Address1Shippingmethodcode      int    `json:"address1_shippingmethodcode"`
		Address1Stateorprovince         string `json:"address1_stateorprovince"`
		Address1Telephone1              string `json:"address1_telephone1"`
		Address1Telephone2              string `json:"address1_telephone2"`
		Address1Telephone3              string `json:"address1_telephone3"`
		Address1Upszone                 string `json:"address1_upszone"`
		Address1Utcoffset               int    `json:"address1_utcoffset"`
		Address2Addressid               string `json:"address2_addressid"`
		Address2Addresstypecode         int    `json:"address2_addresstypecode"`
		Address2City                    string `json:"address2_city"`
		Address2Composite               string `json:"address2_composite"`
		Address2Country                 string `json:"address2_country"`
		Address2County                  string `json:"address2_county"`
		Address2Fax                     string `json:"address2_fax"`
		Address2Freighttermscode        int    `json:"address2_freighttermscode"`
		Address2Latitude                int    `json:"address2_latitude"`
		Address2Line1                   string `json:"address2_line1"`
		Address2Line2                   string `json:"address2_line2"`
		Address2Line3                   string `json:"address2_line3"`
		Address2Longitude               int    `json:"address2_longitude"`
		Address2Name                    string `json:"address2_name"`
		Address2Postalcode              string `json:"address2_postalcode"`
		Address2Postofficebox           string `json:"address2_postofficebox"`
		Address2Primarycontactname      string `json:"address2_primarycontactname"`
		Address2Shippingmethodcode      int    `json:"address2_shippingmethodcode"`
		Address2Stateorprovince         string `json:"address2_stateorprovince"`
		Address2Telephone1              string `json:"address2_telephone1"`
		Address2Telephone2              string `json:"address2_telephone2"`
		Address2Telephone3              string `json:"address2_telephone3"`
		Address2Upszone                 string `json:"address2_upszone"`
		Address2Utcoffset               int    `json:"address2_utcoffset"`
		Address3Addressid               string `json:"address3_addressid"`
		Address3Addresstypecode         int    `json:"address3_addresstypecode"`
		Address3City                    string `json:"address3_city"`
		Address3Composite               string `json:"address3_composite"`
		Address3Country                 string `json:"address3_country"`
		Address3County                  string `json:"address3_county"`
		Address3Fax                     string `json:"address3_fax"`
		Address3Freighttermscode        int    `json:"address3_freighttermscode"`
		Address3Latitude                int    `json:"address3_latitude"`
		Address3Line1                   string `json:"address3_line1"`
		Address3Line2                   string `json:"address3_line2"`
		Address3Line3                   string `json:"address3_line3"`
		Address3Longitude               int    `json:"address3_longitude"`
		Address3Name                    string `json:"address3_name"`
		Address3Postalcode              string `json:"address3_postalcode"`
		Address3Postofficebox           string `json:"address3_postofficebox"`
		Address3Primarycontactname      string `json:"address3_primarycontactname"`
		Address3Shippingmethodcode      int    `json:"address3_shippingmethodcode"`
		Address3Stateorprovince         string `json:"address3_stateorprovince"`
		Address3Telephone1              string `json:"address3_telephone1"`
		Address3Telephone2              string `json:"address3_telephone2"`
		Address3Telephone3              string `json:"address3_telephone3"`
		Address3Upszone                 string `json:"address3_upszone"`
		Address3Utcoffset               int    `json:"address3_utcoffset"`
		Aging30                         int    `json:"aging30"`
		Aging30Base                     int    `json:"aging30_base"`
		Aging60                         int    `json:"aging60"`
		Aging60Base                     int    `json:"aging60_base"`
		Aging90                         int    `json:"aging90"`
		Aging90Base                     int    `json:"aging90_base"`
		Anniversary                     int    `json:"anniversary"`
		Annualincome                    int    `json:"annualincome"`
		AnnualincomeBase                int    `json:"annualincome_base"`
		Assistantname                   string `json:"assistantname"`
		Assistantphone                  string `json:"assistantphone"`
		Birthdate                       int    `json:"birthdate"`
		Business2                       string `json:"business2"`
		Callback                        string `json:"callback"`
		Childrensnames                  string `json:"childrensnames"`
		Company                         string `json:"company"`
		Contactid                       string `json:"contactid"`
		Createdby                       string `json:"createdby"`
		Createdon                       int    `json:"createdon"`
		Createdonbehalfby               string `json:"createdonbehalfby"`
		Creditlimit                     int    `json:"creditlimit"`
		CreditlimitBase                 int    `json:"creditlimit_base"`
		Creditonhold                    bool   `json:"creditonhold"`
		Customersizecode                int    `json:"customersizecode"`
		Customertypecode                int    `json:"customertypecode"`
		Defaultpricelevelid             string `json:"defaultpricelevelid"`
		Department                      string `json:"department"`
		Description                     string `json:"description"`
		Donotbulkemail                  bool   `json:"donotbulkemail"`
		Donotbulkpostalmail             bool   `json:"donotbulkpostalmail"`
		Donotemail                      bool   `json:"donotemail"`
		Donotfax                        bool   `json:"donotfax"`
		Donotphone                      bool   `json:"donotphone"`
		Donotpostalmail                 bool   `json:"donotpostalmail"`
		Donotsendmm                     bool   `json:"donotsendmm"`
		Educationcode                   int    `json:"educationcode"`
		Emailaddress1                   string `json:"emailaddress1"`
		Emailaddress2                   string `json:"emailaddress2"`
		Emailaddress3                   string `json:"emailaddress3"`
		Employeeid                      string `json:"employeeid"`
		Entityimage                     string `json:"entityimage"`
		EntityimageTimestamp            int    `json:"entityimage_timestamp"`
		EntityimageURL                  string `json:"entityimage_url"`
		Entityimageid                   string `json:"entityimageid"`
		Exchangerate                    int    `json:"exchangerate"`
		Externaluseridentifier          string `json:"externaluseridentifier"`
		Familystatuscode                int    `json:"familystatuscode"`
		Fax                             string `json:"fax"`
		Firstname                       string `json:"firstname"`
		Followemail                     bool   `json:"followemail"`
		Ftpsiteurl                      string `json:"ftpsiteurl"`
		Fullname                        string `json:"fullname"`
		Gendercode                      int    `json:"gendercode"`
		Governmentid                    string `json:"governmentid"`
		Haschildrencode                 int    `json:"haschildrencode"`
		Home2                           string `json:"home2"`
		Importsequencenumber            int    `json:"importsequencenumber"`
		Isbackofficecustomer            bool   `json:"isbackofficecustomer"`
		Jobtitle                        string `json:"jobtitle"`
		Lastname                        string `json:"lastname"`
		Lastonholdtime                  int    `json:"lastonholdtime"`
		Lastusedincampaign              int    `json:"lastusedincampaign"`
		Leadsourcecode                  int    `json:"leadsourcecode"`
		Managername                     string `json:"managername"`
		Managerphone                    string `json:"managerphone"`
		Marketingonly                   bool   `json:"marketingonly"`
		Masterid                        string `json:"masterid"`
		Merged                          bool   `json:"merged"`
		Middlename                      string `json:"middlename"`
		Mobilephone                     string `json:"mobilephone"`
		Modifiedby                      string `json:"modifiedby"`
		Modifiedon                      int    `json:"modifiedon"`
		Modifiedonbehalfby              string `json:"modifiedonbehalfby"`
		Nickname                        string `json:"nickname"`
		Numberofchildren                int    `json:"numberofchildren"`
		Onholdtime                      int    `json:"onholdtime"`
		Originatingleadid               string `json:"originatingleadid"`
		Overriddencreatedon             int    `json:"overriddencreatedon"`
		Ownerid                         string `json:"ownerid"`
		Owningbusinessunit              string `json:"owningbusinessunit"`
		Owningteam                      string `json:"owningteam"`
		Owninguser                      string `json:"owninguser"`
		Pager                           string `json:"pager"`
		Parentcustomerid                string `json:"parentcustomerid"`
		ParentcustomeridAccount         string `json:"parentcustomerid_account"`
		ParentcustomeridContact         string `json:"parentcustomerid_contact"`
		Participatesinworkflow          bool   `json:"participatesinworkflow"`
		Paymenttermscode                int    `json:"paymenttermscode"`
		Preferredappointmentdaycode     int    `json:"preferredappointmentdaycode"`
		Preferredappointmenttimecode    int    `json:"preferredappointmenttimecode"`
		Preferredcontactmethodcode      int    `json:"preferredcontactmethodcode"`
		Preferredequipmentid            string `json:"preferredequipmentid"`
		Preferredserviceid              string `json:"preferredserviceid"`
		Preferredsystemuserid           string `json:"preferredsystemuserid"`
		Processid                       string `json:"processid"`
		Salutation                      string `json:"salutation"`
		Shippingmethodcode              int    `json:"shippingmethodcode"`
		SLAContactSLA                   string `json:"sla_contact_sla"`
		SlainvokedidContactSLA          string `json:"slainvokedid_contact_sla"`
		Spousesname                     string `json:"spousesname"`
		Stageid                         string `json:"stageid"`
		StageidProcessstage             string `json:"stageid_processstage"`
		Statecode                       int    `json:"statecode"`
		Statuscode                      int    `json:"statuscode"`
		Subscriptionid                  string `json:"subscriptionid"`
		Suffix                          string `json:"suffix"`
		Telephone1                      string `json:"telephone1"`
		Telephone2                      string `json:"telephone2"`
		Telephone3                      string `json:"telephone3"`
		Territorycode                   int    `json:"territorycode"`
		Timespentbymeonemailandmeetings string `json:"timespentbymeonemailandmeetings"`
		Timezoneruleversionnumber       int    `json:"timezoneruleversionnumber"`
		Transactioncurrencyid           string `json:"transactioncurrencyid"`
		Traversedpath                   string `json:"traversedpath"`
		Utcconversiontimezonecode       int    `json:"utcconversiontimezonecode"`
		Versionnumber                   int    `json:"versionnumber"`
		Websiteurl                      string `json:"websiteurl"`
		Yomifirstname                   string `json:"yomifirstname"`
		Yomifullname                    string `json:"yomifullname"`
		Yomilastname                    string `json:"yomilastname"`
		Yomimiddlename                  string `json:"yomimiddlename"`
	} `json:"attributes"`
	FetchMetaInfo bool `json:"fetchMetaInfo"`
}
type UpdateContacts struct {
	Attributes struct {
		Accountrolecode                 int    `json:"accountrolecode"`
		Address1Addressid               string `json:"address1_addressid"`
		Address1Addresstypecode         int    `json:"address1_addresstypecode"`
		Address1City                    string `json:"address1_city"`
		Address1Composite               string `json:"address1_composite"`
		Address1Country                 string `json:"address1_country"`
		Address1County                  string `json:"address1_county"`
		Address1Fax                     string `json:"address1_fax"`
		Address1Freighttermscode        int    `json:"address1_freighttermscode"`
		Address1Latitude                int    `json:"address1_latitude"`
		Address1Line1                   string `json:"address1_line1"`
		Address1Line2                   string `json:"address1_line2"`
		Address1Line3                   string `json:"address1_line3"`
		Address1Longitude               int    `json:"address1_longitude"`
		Address1Name                    string `json:"address1_name"`
		Address1Postalcode              string `json:"address1_postalcode"`
		Address1Postofficebox           string `json:"address1_postofficebox"`
		Address1Primarycontactname      string `json:"address1_primarycontactname"`
		Address1Shippingmethodcode      int    `json:"address1_shippingmethodcode"`
		Address1Stateorprovince         string `json:"address1_stateorprovince"`
		Address1Telephone1              string `json:"address1_telephone1"`
		Address1Telephone2              string `json:"address1_telephone2"`
		Address1Telephone3              string `json:"address1_telephone3"`
		Address1Upszone                 string `json:"address1_upszone"`
		Address1Utcoffset               int    `json:"address1_utcoffset"`
		Address2Addressid               string `json:"address2_addressid"`
		Address2Addresstypecode         int    `json:"address2_addresstypecode"`
		Address2City                    string `json:"address2_city"`
		Address2Composite               string `json:"address2_composite"`
		Address2Country                 string `json:"address2_country"`
		Address2County                  string `json:"address2_county"`
		Address2Fax                     string `json:"address2_fax"`
		Address2Freighttermscode        int    `json:"address2_freighttermscode"`
		Address2Latitude                int    `json:"address2_latitude"`
		Address2Line1                   string `json:"address2_line1"`
		Address2Line2                   string `json:"address2_line2"`
		Address2Line3                   string `json:"address2_line3"`
		Address2Longitude               int    `json:"address2_longitude"`
		Address2Name                    string `json:"address2_name"`
		Address2Postalcode              string `json:"address2_postalcode"`
		Address2Postofficebox           string `json:"address2_postofficebox"`
		Address2Primarycontactname      string `json:"address2_primarycontactname"`
		Address2Shippingmethodcode      int    `json:"address2_shippingmethodcode"`
		Address2Stateorprovince         string `json:"address2_stateorprovince"`
		Address2Telephone1              string `json:"address2_telephone1"`
		Address2Telephone2              string `json:"address2_telephone2"`
		Address2Telephone3              string `json:"address2_telephone3"`
		Address2Upszone                 string `json:"address2_upszone"`
		Address2Utcoffset               int    `json:"address2_utcoffset"`
		Address3Addressid               string `json:"address3_addressid"`
		Address3Addresstypecode         int    `json:"address3_addresstypecode"`
		Address3City                    string `json:"address3_city"`
		Address3Composite               string `json:"address3_composite"`
		Address3Country                 string `json:"address3_country"`
		Address3County                  string `json:"address3_county"`
		Address3Fax                     string `json:"address3_fax"`
		Address3Freighttermscode        int    `json:"address3_freighttermscode"`
		Address3Latitude                int    `json:"address3_latitude"`
		Address3Line1                   string `json:"address3_line1"`
		Address3Line2                   string `json:"address3_line2"`
		Address3Line3                   string `json:"address3_line3"`
		Address3Longitude               int    `json:"address3_longitude"`
		Address3Name                    string `json:"address3_name"`
		Address3Postalcode              string `json:"address3_postalcode"`
		Address3Postofficebox           string `json:"address3_postofficebox"`
		Address3Primarycontactname      string `json:"address3_primarycontactname"`
		Address3Shippingmethodcode      int    `json:"address3_shippingmethodcode"`
		Address3Stateorprovince         string `json:"address3_stateorprovince"`
		Address3Telephone1              string `json:"address3_telephone1"`
		Address3Telephone2              string `json:"address3_telephone2"`
		Address3Telephone3              string `json:"address3_telephone3"`
		Address3Upszone                 string `json:"address3_upszone"`
		Address3Utcoffset               int    `json:"address3_utcoffset"`
		Aging30                         int    `json:"aging30"`
		Aging30Base                     int    `json:"aging30_base"`
		Aging60                         int    `json:"aging60"`
		Aging60Base                     int    `json:"aging60_base"`
		Aging90                         int    `json:"aging90"`
		Aging90Base                     int    `json:"aging90_base"`
		Anniversary                     int    `json:"anniversary"`
		Annualincome                    int    `json:"annualincome"`
		AnnualincomeBase                int    `json:"annualincome_base"`
		Assistantname                   string `json:"assistantname"`
		Assistantphone                  string `json:"assistantphone"`
		Birthdate                       int    `json:"birthdate"`
		Business2                       string `json:"business2"`
		Callback                        string `json:"callback"`
		Childrensnames                  string `json:"childrensnames"`
		Company                         string `json:"company"`
		Contactid                       string `json:"contactid"`
		Createdby                       string `json:"createdby"`
		Createdon                       int    `json:"createdon"`
		Createdonbehalfby               string `json:"createdonbehalfby"`
		Creditlimit                     int    `json:"creditlimit"`
		CreditlimitBase                 int    `json:"creditlimit_base"`
		Creditonhold                    bool   `json:"creditonhold"`
		Customersizecode                int    `json:"customersizecode"`
		Customertypecode                int    `json:"customertypecode"`
		Defaultpricelevelid             string `json:"defaultpricelevelid"`
		Department                      string `json:"department"`
		Description                     string `json:"description"`
		Donotbulkemail                  bool   `json:"donotbulkemail"`
		Donotbulkpostalmail             bool   `json:"donotbulkpostalmail"`
		Donotemail                      bool   `json:"donotemail"`
		Donotfax                        bool   `json:"donotfax"`
		Donotphone                      bool   `json:"donotphone"`
		Donotpostalmail                 bool   `json:"donotpostalmail"`
		Donotsendmm                     bool   `json:"donotsendmm"`
		Educationcode                   int    `json:"educationcode"`
		Emailaddress1                   string `json:"emailaddress1"`
		Emailaddress2                   string `json:"emailaddress2"`
		Emailaddress3                   string `json:"emailaddress3"`
		Employeeid                      string `json:"employeeid"`
		Entityimage                     string `json:"entityimage"`
		EntityimageTimestamp            int    `json:"entityimage_timestamp"`
		EntityimageURL                  string `json:"entityimage_url"`
		Entityimageid                   string `json:"entityimageid"`
		Exchangerate                    int    `json:"exchangerate"`
		Externaluseridentifier          string `json:"externaluseridentifier"`
		Familystatuscode                int    `json:"familystatuscode"`
		Fax                             string `json:"fax"`
		Firstname                       string `json:"firstname"`
		Followemail                     bool   `json:"followemail"`
		Ftpsiteurl                      string `json:"ftpsiteurl"`
		Fullname                        string `json:"fullname"`
		Gendercode                      int    `json:"gendercode"`
		Governmentid                    string `json:"governmentid"`
		Haschildrencode                 int    `json:"haschildrencode"`
		Home2                           string `json:"home2"`
		Importsequencenumber            int    `json:"importsequencenumber"`
		Isbackofficecustomer            bool   `json:"isbackofficecustomer"`
		Jobtitle                        string `json:"jobtitle"`
		Lastname                        string `json:"lastname"`
		Lastonholdtime                  int    `json:"lastonholdtime"`
		Lastusedincampaign              int    `json:"lastusedincampaign"`
		Leadsourcecode                  int    `json:"leadsourcecode"`
		Managername                     string `json:"managername"`
		Managerphone                    string `json:"managerphone"`
		Marketingonly                   bool   `json:"marketingonly"`
		Masterid                        string `json:"masterid"`
		Merged                          bool   `json:"merged"`
		Middlename                      string `json:"middlename"`
		Mobilephone                     string `json:"mobilephone"`
		Modifiedby                      string `json:"modifiedby"`
		Modifiedon                      int    `json:"modifiedon"`
		Modifiedonbehalfby              string `json:"modifiedonbehalfby"`
		Nickname                        string `json:"nickname"`
		Numberofchildren                int    `json:"numberofchildren"`
		Onholdtime                      int    `json:"onholdtime"`
		Originatingleadid               string `json:"originatingleadid"`
		Overriddencreatedon             int    `json:"overriddencreatedon"`
		Ownerid                         string `json:"ownerid"`
		Owningbusinessunit              string `json:"owningbusinessunit"`
		Owningteam                      string `json:"owningteam"`
		Owninguser                      string `json:"owninguser"`
		Pager                           string `json:"pager"`
		Parentcustomerid                string `json:"parentcustomerid"`
		ParentcustomeridAccount         string `json:"parentcustomerid_account"`
		ParentcustomeridContact         string `json:"parentcustomerid_contact"`
		Participatesinworkflow          bool   `json:"participatesinworkflow"`
		Paymenttermscode                int    `json:"paymenttermscode"`
		Preferredappointmentdaycode     int    `json:"preferredappointmentdaycode"`
		Preferredappointmenttimecode    int    `json:"preferredappointmenttimecode"`
		Preferredcontactmethodcode      int    `json:"preferredcontactmethodcode"`
		Preferredequipmentid            string `json:"preferredequipmentid"`
		Preferredserviceid              string `json:"preferredserviceid"`
		Preferredsystemuserid           string `json:"preferredsystemuserid"`
		Processid                       string `json:"processid"`
		Salutation                      string `json:"salutation"`
		Shippingmethodcode              int    `json:"shippingmethodcode"`
		SLAContactSLA                   string `json:"sla_contact_sla"`
		SlainvokedidContactSLA          string `json:"slainvokedid_contact_sla"`
		Spousesname                     string `json:"spousesname"`
		Stageid                         string `json:"stageid"`
		StageidProcessstage             string `json:"stageid_processstage"`
		Statecode                       int    `json:"statecode"`
		Statuscode                      int    `json:"statuscode"`
		Subscriptionid                  string `json:"subscriptionid"`
		Suffix                          string `json:"suffix"`
		Telephone1                      string `json:"telephone1"`
		Telephone2                      string `json:"telephone2"`
		Telephone3                      string `json:"telephone3"`
		Territorycode                   int    `json:"territorycode"`
		Timespentbymeonemailandmeetings string `json:"timespentbymeonemailandmeetings"`
		Timezoneruleversionnumber       int    `json:"timezoneruleversionnumber"`
		Transactioncurrencyid           string `json:"transactioncurrencyid"`
		Traversedpath                   string `json:"traversedpath"`
		Utcconversiontimezonecode       int    `json:"utcconversiontimezonecode"`
		Versionnumber                   int    `json:"versionnumber"`
		Websiteurl                      string `json:"websiteurl"`
		Yomifirstname                   string `json:"yomifirstname"`
		Yomifullname                    string `json:"yomifullname"`
		Yomilastname                    string `json:"yomilastname"`
		Yomimiddlename                  string `json:"yomimiddlename"`
	} `json:"attributes"`
	FetchMetaInfo bool `json:"fetchMetaInfo"`
}
