package crm_structures

type GetActivities struct {
	Attributes struct {
		Activityadditionalparams                       string `json:"activityadditionalparams"`
		Activityid                                     string `json:"activityid"`
		Activitytypecode                               string `json:"activitytypecode"`
		Actualdurationminutes                          int    `json:"actualdurationminutes"`
		Actualend                                      int    `json:"actualend"`
		Actualstart                                    int    `json:"actualstart"`
		Allparties                                     string `json:"allparties"`
		Community                                      int    `json:"community"`
		Createdby                                      string `json:"createdby"`
		Createdon                                      int    `json:"createdon"`
		Createdonbehalfby                              string `json:"createdonbehalfby"`
		Deliverylastattemptedon                        int    `json:"deliverylastattemptedon"`
		Deliveryprioritycode                           int    `json:"deliveryprioritycode"`
		Description                                    string `json:"description"`
		Exchangeitemid                                 string `json:"exchangeitemid"`
		Exchangerate                                   int    `json:"exchangerate"`
		Exchangeweblink                                string `json:"exchangeweblink"`
		Instancetypecode                               int    `json:"instancetypecode"`
		Isbilled                                       bool   `json:"isbilled"`
		Ismapiprivate                                  bool   `json:"ismapiprivate"`
		Isregularactivity                              bool   `json:"isregularactivity"`
		Isworkflowcreated                              bool   `json:"isworkflowcreated"`
		Lastonholdtime                                 int    `json:"lastonholdtime"`
		Leftvoicemail                                  bool   `json:"leftvoicemail"`
		Modifiedby                                     string `json:"modifiedby"`
		Modifiedon                                     int    `json:"modifiedon"`
		Modifiedonbehalfby                             string `json:"modifiedonbehalfby"`
		Onholdtime                                     int    `json:"onholdtime"`
		Ownerid                                        string `json:"ownerid"`
		Owningbusinessunit                             string `json:"owningbusinessunit"`
		Owningteam                                     string `json:"owningteam"`
		Owninguser                                     string `json:"owninguser"`
		Postponeactivityprocessinguntil                int    `json:"postponeactivityprocessinguntil"`
		Prioritycode                                   int    `json:"prioritycode"`
		Processid                                      string `json:"processid"`
		Regardingobjectid                              string `json:"regardingobjectid"`
		RegardingobjectidAccount                       string `json:"regardingobjectid_account"`
		RegardingobjectidBookableresourcebooking       string `json:"regardingobjectid_bookableresourcebooking"`
		RegardingobjectidBookableresourcebookingheader string `json:"regardingobjectid_bookableresourcebookingheader"`
		RegardingobjectidBulkoperation                 string `json:"regardingobjectid_bulkoperation"`
		RegardingobjectidCampaign                      string `json:"regardingobjectid_campaign"`
		RegardingobjectidCampaignactivity              string `json:"regardingobjectid_campaignactivity"`
		RegardingobjectidContact                       string `json:"regardingobjectid_contact"`
		RegardingobjectidContract                      string `json:"regardingobjectid_contract"`
		RegardingobjectidEntitlement                   string `json:"regardingobjectid_entitlement"`
		RegardingobjectidEntitlementtemplate           string `json:"regardingobjectid_entitlementtemplate"`
		RegardingobjectidIncident                      string `json:"regardingobjectid_incident"`
		RegardingobjectidInvoice                       string `json:"regardingobjectid_invoice"`
		RegardingobjectidKnowledgearticle              string `json:"regardingobjectid_knowledgearticle"`
		RegardingobjectidKnowledgebaserecord           string `json:"regardingobjectid_knowledgebaserecord"`
		RegardingobjectidLead                          string `json:"regardingobjectid_lead"`
		RegardingobjectidNewInteractionforemail        string `json:"regardingobjectid_new_interactionforemail"`
		RegardingobjectidOpportunity                   string `json:"regardingobjectid_opportunity"`
		RegardingobjectidQuote                         string `json:"regardingobjectid_quote"`
		RegardingobjectidSalesorder                    string `json:"regardingobjectid_salesorder"`
		Scheduleddurationminutes                       int    `json:"scheduleddurationminutes"`
		Scheduledend                                   int    `json:"scheduledend"`
		Scheduledstart                                 int    `json:"scheduledstart"`
		Sendermailboxid                                string `json:"sendermailboxid"`
		Senton                                         int    `json:"senton"`
		Seriesid                                       string `json:"seriesid"`
		Serviceid                                      string `json:"serviceid"`
		SLAActivitypointerSLA                          string `json:"sla_activitypointer_sla"`
		SlainvokedidActivitypointerSLA                 string `json:"slainvokedid_activitypointer_sla"`
		Sortdate                                       int    `json:"sortdate"`
		Stageid                                        string `json:"stageid"`
		Statecode                                      int    `json:"statecode"`
		Statuscode                                     int    `json:"statuscode"`
		Subject                                        string `json:"subject"`
		Timezoneruleversionnumber                      int    `json:"timezoneruleversionnumber"`
		Transactioncurrencyid                          string `json:"transactioncurrencyid"`
		Traversedpath                                  string `json:"traversedpath"`
		Utcconversiontimezonecode                      int    `json:"utcconversiontimezonecode"`
		Versionnumber                                  int    `json:"versionnumber"`
	} `json:"attributes"`
	ID string `json:"id"`
}
