package crm_structures

type CreateTasks struct {
	Attributes struct {
		Activityadditionalparams                           string `json:"activityadditionalparams"`
		Activityid                                         string `json:"activityid"`
		ActivityidActivitypointer                          string `json:"activityid_activitypointer"`
		Activitytypecode                                   string `json:"activitytypecode"`
		Actualdurationminutes                              int    `json:"actualdurationminutes"`
		Actualend                                          int    `json:"actualend"`
		Actualstart                                        int    `json:"actualstart"`
		Category                                           string `json:"category"`
		Community                                          int    `json:"community"`
		Createdby                                          string `json:"createdby"`
		CreatedbyTask                                      string `json:"createdby_task"`
		Createdon                                          int    `json:"createdon"`
		Createdonbehalfby                                  string `json:"createdonbehalfby"`
		CreatedonbehalfbyTask                              string `json:"createdonbehalfby_task"`
		Crmtaskassigneduniqueid                            string `json:"crmtaskassigneduniqueid"`
		Deliverylastattemptedon                            int    `json:"deliverylastattemptedon"`
		Deliveryprioritycode                               int    `json:"deliveryprioritycode"`
		Description                                        string `json:"description"`
		Exchangeitemid                                     string `json:"exchangeitemid"`
		Exchangerate                                       int    `json:"exchangerate"`
		Exchangeweblink                                    string `json:"exchangeweblink"`
		Importsequencenumber                               int    `json:"importsequencenumber"`
		Instancetypecode                                   int    `json:"instancetypecode"`
		Isbilled                                           bool   `json:"isbilled"`
		Ismapiprivate                                      bool   `json:"ismapiprivate"`
		Isregularactivity                                  bool   `json:"isregularactivity"`
		Isworkflowcreated                                  bool   `json:"isworkflowcreated"`
		Lastonholdtime                                     int    `json:"lastonholdtime"`
		Leftvoicemail                                      bool   `json:"leftvoicemail"`
		Modifiedby                                         string `json:"modifiedby"`
		ModifiedbyTask                                     string `json:"modifiedby_task"`
		Modifiedon                                         int    `json:"modifiedon"`
		Modifiedonbehalfby                                 string `json:"modifiedonbehalfby"`
		ModifiedonbehalfbyTask                             string `json:"modifiedonbehalfby_task"`
		Onholdtime                                         int    `json:"onholdtime"`
		Overriddencreatedon                                int    `json:"overriddencreatedon"`
		Ownerid                                            string `json:"ownerid"`
		Owningbusinessunit                                 string `json:"owningbusinessunit"`
		OwningbusinessunitTask                             string `json:"owningbusinessunit_task"`
		Owningteam                                         string `json:"owningteam"`
		OwningteamTask                                     string `json:"owningteam_task"`
		Owninguser                                         string `json:"owninguser"`
		OwninguserTask                                     string `json:"owninguser_task"`
		Percentcomplete                                    int    `json:"percentcomplete"`
		Postponeactivityprocessinguntil                    int    `json:"postponeactivityprocessinguntil"`
		Prioritycode                                       int    `json:"prioritycode"`
		Processid                                          string `json:"processid"`
		Regardingobjectid                                  string `json:"regardingobjectid"`
		RegardingobjectidAccount                           string `json:"regardingobjectid_account"`
		RegardingobjectidAccountTask                       string `json:"regardingobjectid_account_task"`
		RegardingobjectidBookableresourcebooking           string `json:"regardingobjectid_bookableresourcebooking"`
		RegardingobjectidBookableresourcebookingTask       string `json:"regardingobjectid_bookableresourcebooking_task"`
		RegardingobjectidBookableresourcebookingheader     string `json:"regardingobjectid_bookableresourcebookingheader"`
		RegardingobjectidBookableresourcebookingheaderTask string `json:"regardingobjectid_bookableresourcebookingheader_task"`
		RegardingobjectidBulkoperation                     string `json:"regardingobjectid_bulkoperation"`
		RegardingobjectidCampaign                          string `json:"regardingobjectid_campaign"`
		RegardingobjectidCampaignTask                      string `json:"regardingobjectid_campaign_task"`
		RegardingobjectidCampaignactivity                  string `json:"regardingobjectid_campaignactivity"`
		RegardingobjectidCampaignactivityTask              string `json:"regardingobjectid_campaignactivity_task"`
		RegardingobjectidContact                           string `json:"regardingobjectid_contact"`
		RegardingobjectidContactTask                       string `json:"regardingobjectid_contact_task"`
		RegardingobjectidContract                          string `json:"regardingobjectid_contract"`
		RegardingobjectidContractTask                      string `json:"regardingobjectid_contract_task"`
		RegardingobjectidEntitlement                       string `json:"regardingobjectid_entitlement"`
		RegardingobjectidEntitlementTask                   string `json:"regardingobjectid_entitlement_task"`
		RegardingobjectidEntitlementtemplate               string `json:"regardingobjectid_entitlementtemplate"`
		RegardingobjectidEntitlementtemplateTask           string `json:"regardingobjectid_entitlementtemplate_task"`
		RegardingobjectidIncident                          string `json:"regardingobjectid_incident"`
		RegardingobjectidIncidentTask                      string `json:"regardingobjectid_incident_task"`
		RegardingobjectidInvoice                           string `json:"regardingobjectid_invoice"`
		RegardingobjectidInvoiceTask                       string `json:"regardingobjectid_invoice_task"`
		RegardingobjectidKnowledgearticle                  string `json:"regardingobjectid_knowledgearticle"`
		RegardingobjectidKnowledgearticleTask              string `json:"regardingobjectid_knowledgearticle_task"`
		RegardingobjectidKnowledgebaserecord               string `json:"regardingobjectid_knowledgebaserecord"`
		RegardingobjectidKnowledgebaserecordTask           string `json:"regardingobjectid_knowledgebaserecord_task"`
		RegardingobjectidLead                              string `json:"regardingobjectid_lead"`
		RegardingobjectidLeadTask                          string `json:"regardingobjectid_lead_task"`
		RegardingobjectidNewInteractionforemail            string `json:"regardingobjectid_new_interactionforemail"`
		RegardingobjectidOpportunity                       string `json:"regardingobjectid_opportunity"`
		RegardingobjectidOpportunityTask                   string `json:"regardingobjectid_opportunity_task"`
		RegardingobjectidQuote                             string `json:"regardingobjectid_quote"`
		RegardingobjectidQuoteTask                         string `json:"regardingobjectid_quote_task"`
		RegardingobjectidSalesorder                        string `json:"regardingobjectid_salesorder"`
		RegardingobjectidSalesorderTask                    string `json:"regardingobjectid_salesorder_task"`
		Scheduleddurationminutes                           int    `json:"scheduleddurationminutes"`
		Scheduledend                                       int    `json:"scheduledend"`
		Scheduledstart                                     int    `json:"scheduledstart"`
		Sendermailboxid                                    string `json:"sendermailboxid"`
		Senton                                             int    `json:"senton"`
		Seriesid                                           string `json:"seriesid"`
		Serviceid                                          string `json:"serviceid"`
		ServiceidTask                                      string `json:"serviceid_task"`
		SLAActivitypointerSLA                              string `json:"sla_activitypointer_sla"`
		SLATaskSLA                                         string `json:"sla_task_sla"`
		SlainvokedidActivitypointerSLA                     string `json:"slainvokedid_activitypointer_sla"`
		SlainvokedidTaskSLA                                string `json:"slainvokedid_task_sla"`
		Sortdate                                           int    `json:"sortdate"`
		Stageid                                            string `json:"stageid"`
		StageidProcessstage                                string `json:"stageid_processstage"`
		Statecode                                          int    `json:"statecode"`
		Statuscode                                         int    `json:"statuscode"`
		Subcategory                                        string `json:"subcategory"`
		Subject                                            string `json:"subject"`
		Subscriptionid                                     string `json:"subscriptionid"`
		Timezoneruleversionnumber                          int    `json:"timezoneruleversionnumber"`
		Transactioncurrencyid                              string `json:"transactioncurrencyid"`
		TransactioncurrencyidTask                          string `json:"transactioncurrencyid_task"`
		Traversedpath                                      string `json:"traversedpath"`
		Utcconversiontimezonecode                          int    `json:"utcconversiontimezonecode"`
		Versionnumber                                      int    `json:"versionnumber"`
	} `json:"attributes"`
	FetchMetaInfo bool `json:"fetchMetaInfo"`
}
type GetTasks struct {
	Attributes struct {
		Activityadditionalparams                           string `json:"activityadditionalparams"`
		Activityid                                         string `json:"activityid"`
		ActivityidActivitypointer                          string `json:"activityid_activitypointer"`
		Activitytypecode                                   string `json:"activitytypecode"`
		Actualdurationminutes                              int    `json:"actualdurationminutes"`
		Actualend                                          int    `json:"actualend"`
		Actualstart                                        int    `json:"actualstart"`
		Category                                           string `json:"category"`
		Community                                          int    `json:"community"`
		Createdby                                          string `json:"createdby"`
		CreatedbyTask                                      string `json:"createdby_task"`
		Createdon                                          int    `json:"createdon"`
		Createdonbehalfby                                  string `json:"createdonbehalfby"`
		CreatedonbehalfbyTask                              string `json:"createdonbehalfby_task"`
		Crmtaskassigneduniqueid                            string `json:"crmtaskassigneduniqueid"`
		Deliverylastattemptedon                            int    `json:"deliverylastattemptedon"`
		Deliveryprioritycode                               int    `json:"deliveryprioritycode"`
		Description                                        string `json:"description"`
		Exchangeitemid                                     string `json:"exchangeitemid"`
		Exchangerate                                       int    `json:"exchangerate"`
		Exchangeweblink                                    string `json:"exchangeweblink"`
		Importsequencenumber                               int    `json:"importsequencenumber"`
		Instancetypecode                                   int    `json:"instancetypecode"`
		Isbilled                                           bool   `json:"isbilled"`
		Ismapiprivate                                      bool   `json:"ismapiprivate"`
		Isregularactivity                                  bool   `json:"isregularactivity"`
		Isworkflowcreated                                  bool   `json:"isworkflowcreated"`
		Lastonholdtime                                     int    `json:"lastonholdtime"`
		Leftvoicemail                                      bool   `json:"leftvoicemail"`
		Modifiedby                                         string `json:"modifiedby"`
		ModifiedbyTask                                     string `json:"modifiedby_task"`
		Modifiedon                                         int    `json:"modifiedon"`
		Modifiedonbehalfby                                 string `json:"modifiedonbehalfby"`
		ModifiedonbehalfbyTask                             string `json:"modifiedonbehalfby_task"`
		Onholdtime                                         int    `json:"onholdtime"`
		Overriddencreatedon                                int    `json:"overriddencreatedon"`
		Ownerid                                            string `json:"ownerid"`
		Owningbusinessunit                                 string `json:"owningbusinessunit"`
		OwningbusinessunitTask                             string `json:"owningbusinessunit_task"`
		Owningteam                                         string `json:"owningteam"`
		OwningteamTask                                     string `json:"owningteam_task"`
		Owninguser                                         string `json:"owninguser"`
		OwninguserTask                                     string `json:"owninguser_task"`
		Percentcomplete                                    int    `json:"percentcomplete"`
		Postponeactivityprocessinguntil                    int    `json:"postponeactivityprocessinguntil"`
		Prioritycode                                       int    `json:"prioritycode"`
		Processid                                          string `json:"processid"`
		Regardingobjectid                                  string `json:"regardingobjectid"`
		RegardingobjectidAccount                           string `json:"regardingobjectid_account"`
		RegardingobjectidAccountTask                       string `json:"regardingobjectid_account_task"`
		RegardingobjectidBookableresourcebooking           string `json:"regardingobjectid_bookableresourcebooking"`
		RegardingobjectidBookableresourcebookingTask       string `json:"regardingobjectid_bookableresourcebooking_task"`
		RegardingobjectidBookableresourcebookingheader     string `json:"regardingobjectid_bookableresourcebookingheader"`
		RegardingobjectidBookableresourcebookingheaderTask string `json:"regardingobjectid_bookableresourcebookingheader_task"`
		RegardingobjectidBulkoperation                     string `json:"regardingobjectid_bulkoperation"`
		RegardingobjectidCampaign                          string `json:"regardingobjectid_campaign"`
		RegardingobjectidCampaignTask                      string `json:"regardingobjectid_campaign_task"`
		RegardingobjectidCampaignactivity                  string `json:"regardingobjectid_campaignactivity"`
		RegardingobjectidCampaignactivityTask              string `json:"regardingobjectid_campaignactivity_task"`
		RegardingobjectidContact                           string `json:"regardingobjectid_contact"`
		RegardingobjectidContactTask                       string `json:"regardingobjectid_contact_task"`
		RegardingobjectidContract                          string `json:"regardingobjectid_contract"`
		RegardingobjectidContractTask                      string `json:"regardingobjectid_contract_task"`
		RegardingobjectidEntitlement                       string `json:"regardingobjectid_entitlement"`
		RegardingobjectidEntitlementTask                   string `json:"regardingobjectid_entitlement_task"`
		RegardingobjectidEntitlementtemplate               string `json:"regardingobjectid_entitlementtemplate"`
		RegardingobjectidEntitlementtemplateTask           string `json:"regardingobjectid_entitlementtemplate_task"`
		RegardingobjectidIncident                          string `json:"regardingobjectid_incident"`
		RegardingobjectidIncidentTask                      string `json:"regardingobjectid_incident_task"`
		RegardingobjectidInvoice                           string `json:"regardingobjectid_invoice"`
		RegardingobjectidInvoiceTask                       string `json:"regardingobjectid_invoice_task"`
		RegardingobjectidKnowledgearticle                  string `json:"regardingobjectid_knowledgearticle"`
		RegardingobjectidKnowledgearticleTask              string `json:"regardingobjectid_knowledgearticle_task"`
		RegardingobjectidKnowledgebaserecord               string `json:"regardingobjectid_knowledgebaserecord"`
		RegardingobjectidKnowledgebaserecordTask           string `json:"regardingobjectid_knowledgebaserecord_task"`
		RegardingobjectidLead                              string `json:"regardingobjectid_lead"`
		RegardingobjectidLeadTask                          string `json:"regardingobjectid_lead_task"`
		RegardingobjectidNewInteractionforemail            string `json:"regardingobjectid_new_interactionforemail"`
		RegardingobjectidOpportunity                       string `json:"regardingobjectid_opportunity"`
		RegardingobjectidOpportunityTask                   string `json:"regardingobjectid_opportunity_task"`
		RegardingobjectidQuote                             string `json:"regardingobjectid_quote"`
		RegardingobjectidQuoteTask                         string `json:"regardingobjectid_quote_task"`
		RegardingobjectidSalesorder                        string `json:"regardingobjectid_salesorder"`
		RegardingobjectidSalesorderTask                    string `json:"regardingobjectid_salesorder_task"`
		Scheduleddurationminutes                           int    `json:"scheduleddurationminutes"`
		Scheduledend                                       int    `json:"scheduledend"`
		Scheduledstart                                     int    `json:"scheduledstart"`
		Sendermailboxid                                    string `json:"sendermailboxid"`
		Senton                                             int    `json:"senton"`
		Seriesid                                           string `json:"seriesid"`
		Serviceid                                          string `json:"serviceid"`
		ServiceidTask                                      string `json:"serviceid_task"`
		SLAActivitypointerSLA                              string `json:"sla_activitypointer_sla"`
		SLATaskSLA                                         string `json:"sla_task_sla"`
		SlainvokedidActivitypointerSLA                     string `json:"slainvokedid_activitypointer_sla"`
		SlainvokedidTaskSLA                                string `json:"slainvokedid_task_sla"`
		Sortdate                                           int    `json:"sortdate"`
		Stageid                                            string `json:"stageid"`
		StageidProcessstage                                string `json:"stageid_processstage"`
		Statecode                                          int    `json:"statecode"`
		Statuscode                                         int    `json:"statuscode"`
		Subcategory                                        string `json:"subcategory"`
		Subject                                            string `json:"subject"`
		Subscriptionid                                     string `json:"subscriptionid"`
		Timezoneruleversionnumber                          int    `json:"timezoneruleversionnumber"`
		Transactioncurrencyid                              string `json:"transactioncurrencyid"`
		TransactioncurrencyidTask                          string `json:"transactioncurrencyid_task"`
		Traversedpath                                      string `json:"traversedpath"`
		Utcconversiontimezonecode                          int    `json:"utcconversiontimezonecode"`
		Versionnumber                                      int    `json:"versionnumber"`
	} `json:"attributes"`
	FetchMetaInfo bool   `json:"fetchMetaInfo"`
	ID            string `json:"id"`
}
type UpdateTasks struct {
	Attributes struct {
		Activityadditionalparams                           string `json:"activityadditionalparams"`
		Activityid                                         string `json:"activityid"`
		ActivityidActivitypointer                          string `json:"activityid_activitypointer"`
		Activitytypecode                                   string `json:"activitytypecode"`
		Actualdurationminutes                              int    `json:"actualdurationminutes"`
		Actualend                                          int    `json:"actualend"`
		Actualstart                                        int    `json:"actualstart"`
		Category                                           string `json:"category"`
		Community                                          int    `json:"community"`
		Createdby                                          string `json:"createdby"`
		CreatedbyTask                                      string `json:"createdby_task"`
		Createdon                                          int    `json:"createdon"`
		Createdonbehalfby                                  string `json:"createdonbehalfby"`
		CreatedonbehalfbyTask                              string `json:"createdonbehalfby_task"`
		Crmtaskassigneduniqueid                            string `json:"crmtaskassigneduniqueid"`
		Deliverylastattemptedon                            int    `json:"deliverylastattemptedon"`
		Deliveryprioritycode                               int    `json:"deliveryprioritycode"`
		Description                                        string `json:"description"`
		Exchangeitemid                                     string `json:"exchangeitemid"`
		Exchangerate                                       int    `json:"exchangerate"`
		Exchangeweblink                                    string `json:"exchangeweblink"`
		Importsequencenumber                               int    `json:"importsequencenumber"`
		Instancetypecode                                   int    `json:"instancetypecode"`
		Isbilled                                           bool   `json:"isbilled"`
		Ismapiprivate                                      bool   `json:"ismapiprivate"`
		Isregularactivity                                  bool   `json:"isregularactivity"`
		Isworkflowcreated                                  bool   `json:"isworkflowcreated"`
		Lastonholdtime                                     int    `json:"lastonholdtime"`
		Leftvoicemail                                      bool   `json:"leftvoicemail"`
		Modifiedby                                         string `json:"modifiedby"`
		ModifiedbyTask                                     string `json:"modifiedby_task"`
		Modifiedon                                         int    `json:"modifiedon"`
		Modifiedonbehalfby                                 string `json:"modifiedonbehalfby"`
		ModifiedonbehalfbyTask                             string `json:"modifiedonbehalfby_task"`
		Onholdtime                                         int    `json:"onholdtime"`
		Overriddencreatedon                                int    `json:"overriddencreatedon"`
		Ownerid                                            string `json:"ownerid"`
		Owningbusinessunit                                 string `json:"owningbusinessunit"`
		OwningbusinessunitTask                             string `json:"owningbusinessunit_task"`
		Owningteam                                         string `json:"owningteam"`
		OwningteamTask                                     string `json:"owningteam_task"`
		Owninguser                                         string `json:"owninguser"`
		OwninguserTask                                     string `json:"owninguser_task"`
		Percentcomplete                                    int    `json:"percentcomplete"`
		Postponeactivityprocessinguntil                    int    `json:"postponeactivityprocessinguntil"`
		Prioritycode                                       int    `json:"prioritycode"`
		Processid                                          string `json:"processid"`
		Regardingobjectid                                  string `json:"regardingobjectid"`
		RegardingobjectidAccount                           string `json:"regardingobjectid_account"`
		RegardingobjectidAccountTask                       string `json:"regardingobjectid_account_task"`
		RegardingobjectidBookableresourcebooking           string `json:"regardingobjectid_bookableresourcebooking"`
		RegardingobjectidBookableresourcebookingTask       string `json:"regardingobjectid_bookableresourcebooking_task"`
		RegardingobjectidBookableresourcebookingheader     string `json:"regardingobjectid_bookableresourcebookingheader"`
		RegardingobjectidBookableresourcebookingheaderTask string `json:"regardingobjectid_bookableresourcebookingheader_task"`
		RegardingobjectidBulkoperation                     string `json:"regardingobjectid_bulkoperation"`
		RegardingobjectidCampaign                          string `json:"regardingobjectid_campaign"`
		RegardingobjectidCampaignTask                      string `json:"regardingobjectid_campaign_task"`
		RegardingobjectidCampaignactivity                  string `json:"regardingobjectid_campaignactivity"`
		RegardingobjectidCampaignactivityTask              string `json:"regardingobjectid_campaignactivity_task"`
		RegardingobjectidContact                           string `json:"regardingobjectid_contact"`
		RegardingobjectidContactTask                       string `json:"regardingobjectid_contact_task"`
		RegardingobjectidContract                          string `json:"regardingobjectid_contract"`
		RegardingobjectidContractTask                      string `json:"regardingobjectid_contract_task"`
		RegardingobjectidEntitlement                       string `json:"regardingobjectid_entitlement"`
		RegardingobjectidEntitlementTask                   string `json:"regardingobjectid_entitlement_task"`
		RegardingobjectidEntitlementtemplate               string `json:"regardingobjectid_entitlementtemplate"`
		RegardingobjectidEntitlementtemplateTask           string `json:"regardingobjectid_entitlementtemplate_task"`
		RegardingobjectidIncident                          string `json:"regardingobjectid_incident"`
		RegardingobjectidIncidentTask                      string `json:"regardingobjectid_incident_task"`
		RegardingobjectidInvoice                           string `json:"regardingobjectid_invoice"`
		RegardingobjectidInvoiceTask                       string `json:"regardingobjectid_invoice_task"`
		RegardingobjectidKnowledgearticle                  string `json:"regardingobjectid_knowledgearticle"`
		RegardingobjectidKnowledgearticleTask              string `json:"regardingobjectid_knowledgearticle_task"`
		RegardingobjectidKnowledgebaserecord               string `json:"regardingobjectid_knowledgebaserecord"`
		RegardingobjectidKnowledgebaserecordTask           string `json:"regardingobjectid_knowledgebaserecord_task"`
		RegardingobjectidLead                              string `json:"regardingobjectid_lead"`
		RegardingobjectidLeadTask                          string `json:"regardingobjectid_lead_task"`
		RegardingobjectidNewInteractionforemail            string `json:"regardingobjectid_new_interactionforemail"`
		RegardingobjectidOpportunity                       string `json:"regardingobjectid_opportunity"`
		RegardingobjectidOpportunityTask                   string `json:"regardingobjectid_opportunity_task"`
		RegardingobjectidQuote                             string `json:"regardingobjectid_quote"`
		RegardingobjectidQuoteTask                         string `json:"regardingobjectid_quote_task"`
		RegardingobjectidSalesorder                        string `json:"regardingobjectid_salesorder"`
		RegardingobjectidSalesorderTask                    string `json:"regardingobjectid_salesorder_task"`
		Scheduleddurationminutes                           int    `json:"scheduleddurationminutes"`
		Scheduledend                                       int    `json:"scheduledend"`
		Scheduledstart                                     int    `json:"scheduledstart"`
		Sendermailboxid                                    string `json:"sendermailboxid"`
		Senton                                             int    `json:"senton"`
		Seriesid                                           string `json:"seriesid"`
		Serviceid                                          string `json:"serviceid"`
		ServiceidTask                                      string `json:"serviceid_task"`
		SLAActivitypointerSLA                              string `json:"sla_activitypointer_sla"`
		SLATaskSLA                                         string `json:"sla_task_sla"`
		SlainvokedidActivitypointerSLA                     string `json:"slainvokedid_activitypointer_sla"`
		SlainvokedidTaskSLA                                string `json:"slainvokedid_task_sla"`
		Sortdate                                           int    `json:"sortdate"`
		Stageid                                            string `json:"stageid"`
		StageidProcessstage                                string `json:"stageid_processstage"`
		Statecode                                          int    `json:"statecode"`
		Statuscode                                         int    `json:"statuscode"`
		Subcategory                                        string `json:"subcategory"`
		Subject                                            string `json:"subject"`
		Subscriptionid                                     string `json:"subscriptionid"`
		Timezoneruleversionnumber                          int    `json:"timezoneruleversionnumber"`
		Transactioncurrencyid                              string `json:"transactioncurrencyid"`
		TransactioncurrencyidTask                          string `json:"transactioncurrencyid_task"`
		Traversedpath                                      string `json:"traversedpath"`
		Utcconversiontimezonecode                          int    `json:"utcconversiontimezonecode"`
		Versionnumber                                      int    `json:"versionnumber"`
	} `json:"attributes"`
	FetchMetaInfo bool `json:"fetchMetaInfo"`
}
